#ifndef SCREENCONSTANTS_H
#define SCREENCONSTANTS_H

#define SCREEN_WIDTH 128 
#define SCREEN_HEIGHT 32
#define OLED_RESET     -1 // Reset pin # (or -1 if sharing Arduino reset pin)
#define SCREEN_ADDRESS 0x3C ///< See datasheet for Address; 0x3D for 128x64, 0x3C for 128x32

#define WELCOME_PHASE 100
#define WELCOME_SCREEN_INTERVAL_UPDATE 500
#define WELCOME_SCREEN_TIMEOUT 2000

#define SELECT_SCREEN_PHASE 200
#define SELECT_SCREEN_INTERVAL_UPDATE 250
#define MAX_SELECT_SCREEN_SELECTION 2

#define HEARTBEAT_MEASURE_PHASE 300
#define HEARTBEAT_MEASURE_SCREEN_INTERVAL_UPDATE 500
#define OUTLINED_HEART 301
#define NORMAL_HEART   302
#define BEAT_HEART     303
#define PANEL_WIDTH    48
#define GRAPH_TOP      18
#define GRAPH_HEIGHT (SCREEN_HEIGHT - GRAPH_TOP)

#define STRESS_MEASURE_PHASE 400

#endif