#ifndef SCREENCONSTANTS_H
#define SCREENCONSTANTS_H

#define SCREEN_WIDTH 128 
#define SCREEN_HEIGHT 32
#define OLED_RESET     -1 
#define SCREEN_ADDRESS 0x3C 

#define WELCOME_PHASE 100
#define WELCOME_SCREEN_INTERVAL_UPDATE 500
#define WELCOME_SCREEN_TIMEOUT 2000

#define SELECT_SCREEN_PHASE 200
#define SELECT_SCREEN_INTERVAL_UPDATE 250
#define MAX_SELECT_SCREEN_SELECTION 2

#define HEARTBEAT_MEASURE_PHASE 300
#define HEARTBEAT_MEASURE_SCREEN_INTERVAL_UPDATE 1000
#define OUTLINED_HEART 301
#define NORMAL_HEART   302
#define BEAT_HEART     303

#define STRESS_MEASURE_PHASE 400

#endif